### ISSUE TITLE
Include additional Dexcom data, such as insulin [enhancement]

### ISSUE THREAD

**Issue by waseltzer** [gagebenne/pydexcom#63]
I'd like to be able to get the additional data provided by the Dexcom API events endpoint, especially insulin.
https://developer.dexcom.com/docs/dexcomv3/operation/getEventsV3/

This would enable me to create Home Assistant automations that would alert on missed long-acting insulin doses. (Ooops.)

Glad to help write the code to do this.

Thanks!

**Comment by carlsondev** [comment]
The default Dexcom API has a 1 hour delay inside the US and a 3 hour delay outside. This is by design according to their documentation. Since the followers don't have access to your events, it's unlikely that the Follow API would, so (as you linked) there would need to be additional support from the official Dexcom API. For something like the use case you gave, the hour delay would probably cause an issue

**Comment by waseltzer** [comment]
Oh, I didn't know about the delay in the Follow API.
Though, that would be fine to tracking insulin usage recorded in the Dexcom app.
(Not OK for tracking glucose, of course, as we need real-time data for low glucose events, etc.)

**Comment by gagebenne** [comment]
Yeah, the one (three) hour delay is the big showstopper, thanks @carlsondev. I have a feeling Dexcom would not issue API tokens for applications for services using both the official Dexcom API and the less-so Share API. Maybe one day Dexcom (FDA?) will just allow users real-time blood glucose access with their official API, then getting things to work with the official API Would become top priority.
